
import java.awt.Cursor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muzer
 */
public class aboutframe extends javax.swing.JFrame {

    /**
     * Creates new form aboutframe
     */
    public aboutframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        vclabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        backlabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        deplabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        unilabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(51, 0, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(null);

        vclabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        vclabel.setForeground(new java.awt.Color(255, 255, 255));
        vclabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vclabel.setText("Vice Chancellor");
        vclabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                vclabelMouseMoved(evt);
            }
        });
        vclabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vclabelMouseClicked(evt);
            }
        });
        jPanel6.add(vclabel);
        vclabel.setBounds(40, 10, 190, 40);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(20, 250, 290, 60);

        jPanel7.setBackground(new java.awt.Color(51, 0, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(null);

        backlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backlabel.setForeground(new java.awt.Color(255, 255, 255));
        backlabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backlabel.setText("BACK");
        backlabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backlabelMouseMoved(evt);
            }
        });
        backlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlabelMouseClicked(evt);
            }
        });
        jPanel7.add(backlabel);
        backlabel.setBounds(40, 10, 120, 40);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(20, 520, 320, 60);

        jPanel8.setBackground(new java.awt.Color(51, 0, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(null);

        deplabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deplabel.setForeground(new java.awt.Color(255, 255, 255));
        deplabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deplabel.setText("Departments");
        deplabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deplabelMouseMoved(evt);
            }
        });
        deplabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deplabelMouseClicked(evt);
            }
        });
        jPanel8.add(deplabel);
        deplabel.setBounds(40, 10, 170, 40);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(20, 340, 300, 60);

        jPanel9.setBackground(new java.awt.Color(51, 0, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(null);

        unilabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        unilabel.setForeground(new java.awt.Color(255, 255, 255));
        unilabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        unilabel.setText("University Auditorium");
        unilabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                unilabelMouseMoved(evt);
            }
        });
        unilabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unilabelMouseClicked(evt);
            }
        });
        jPanel9.add(unilabel);
        unilabel.setBounds(20, 10, 270, 40);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(20, 430, 320, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ABOUT");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 150, 290, 60);
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 680, 90, 70);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 310, 610);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Devi Ahilya University");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 20, 550, 90);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 130);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        jPanel4.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(0, 0, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("--------VISION--------");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 9, 260, 31);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea2.setRows(6);
        jTextArea2.setText("Become a globally recognised\ninstitute in management,\ncomputer science and comme-\nrce through creating an \nenvironment of excellence.");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 40, 260, 140);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(350, 360, 280, 190);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        jPanel5.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(0, 0, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("-------MISSION-------");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 9, 260, 31);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea3.setRows(6);
        jTextArea3.setText("Develop innovative and\nethical future leaders capable \nof managing change and \ntransformation in a globally\ncompettive environment.\n");
        jScrollPane3.setViewportView(jTextArea3);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(10, 40, 260, 140);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(40, 160, 280, 190);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(310, 0, 1090, 610);

        setSize(new java.awt.Dimension(986, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vclabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vclabelMouseMoved

        vclabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        // TODO add your handling code here:
    }//GEN-LAST:event_vclabelMouseMoved

    private void vclabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vclabelMouseClicked
      vicechancellor vc = new vicechancellor();
this.dispose();
vc.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_vclabelMouseClicked

    private void backlabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabelMouseMoved
backlabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
// TODO add your handling code here:
    }//GEN-LAST:event_backlabelMouseMoved

    private void backlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabelMouseClicked
  scsithomeframe ip = new scsithomeframe();
  this.dispose();
  ip.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_backlabelMouseClicked

    private void deplabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deplabelMouseMoved
deplabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_deplabelMouseMoved

    private void deplabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deplabelMouseClicked
departmentframe df = new departmentframe();
this.dispose();
df.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_deplabelMouseClicked

    private void unilabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unilabelMouseMoved
unilabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_unilabelMouseMoved

    private void unilabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unilabelMouseClicked
auditoriumframe af = new auditoriumframe();
this.dispose();
af.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_unilabelMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
vicechancellor vc = new vicechancellor();
this.dispose();
vc.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
departmentframe df = new departmentframe();
this.dispose();
df.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
scsithomeframe ip = new scsithomeframe();
        this.dispose();
        ip.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
auditoriumframe af = new auditoriumframe();
this.dispose();
af.setVisible(true);


// TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aboutframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aboutframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aboutframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aboutframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aboutframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backlabel;
    private javax.swing.JLabel deplabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel unilabel;
    private javax.swing.JLabel vclabel;
    // End of variables declaration//GEN-END:variables
}
