
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muzer
 */
public class addfaculty extends javax.swing.JFrame {
Color panedefault;
    Color paneClick;
    /**
     * Creates new form addfaculty
     */
    public addfaculty() {
        initComponents();
        panedefault = new Color(51, 0, 102);
        paneClick = new Color(255, 255, 255);
        panel1.setBackground(panedefault);
        panel2.setBackground(panedefault);
         panel3.setBackground(panedefault);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resptf = new javax.swing.JTextField();
        idtf = new javax.swing.JTextField();
        nametf = new javax.swing.JTextField();
        qualitf = new javax.swing.JTextField();
        desigtf = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, -10, 310, 160);

        jPanel5.setBackground(new java.awt.Color(51, 0, 102));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Update ");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel5.add(jLabel7);
        jLabel7.setBounds(60, 10, 93, 40);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel5.add(panel2);
        panel2.setBounds(0, 0, 30, 70);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(40, 360, 290, 70);

        jPanel6.setBackground(new java.awt.Color(51, 0, 102));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel6MouseMoved(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add Faculty");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel6.add(jLabel8);
        jLabel8.setBounds(60, 10, 150, 40);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel6.add(panel1);
        panel1.setBounds(0, 0, 30, 70);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(40, 240, 290, 70);

        jPanel7.setBackground(new java.awt.Color(51, 0, 102));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Delete");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jPanel7.add(jLabel9);
        jLabel9.setBounds(60, 10, 90, 40);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel7.add(panel3);
        panel3.setBounds(0, 0, 30, 70);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(40, 470, 290, 70);

        jPanel4.setBackground(new java.awt.Color(51, 0, 102));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Back");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(50, 10, 140, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(40, 570, 290, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, 0, 330, 780);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Responsibility");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(80, 560, 190, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Faculty ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 270, 190, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 340, 190, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Qualification");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 410, 190, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Designation");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(80, 480, 190, 50);

        resptf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(resptf);
        resptf.setBounds(310, 560, 330, 50);

        idtf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(idtf);
        idtf.setBounds(310, 270, 330, 50);

        nametf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(nametf);
        nametf.setBounds(310, 340, 330, 50);

        qualitf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(qualitf);
        qualitf.setBounds(310, 410, 330, 50);

        desigtf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(desigtf);
        desigtf.setBounds(310, 480, 330, 50);

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("    IIPS  FACULTY  MANAGEMENT ");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(140, 20, 630, 80);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 870, 140);

        cb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C_faculty", "M_faculty" }));
        jPanel2.add(cb1);
        cb1.setBounds(320, 190, 310, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Faculty Type");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 200, 170, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("LOAD DATA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(660, 260, 190, 70);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(660, 380, 180, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(310, 0, 870, 780);

        setSize(new java.awt.Dimension(1202, 783));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 Connection conn=null;
   Statement s1;
   PreparedStatement pstmt=null;
   
  
    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked

        String id = idtf.getText();
  String fname = nametf.getText();
   String qualification = qualitf.getText();
        String designation = desigtf.getText();
           String responsibility  = resptf.getText();
           String type =(String) cb1.getSelectedItem().toString();
        
        int x= JOptionPane.showConfirmDialog(null," Do you want to update the record");
if(x==JOptionPane.YES_OPTION ){
   try {
       String query1= "UPDATE " + type + " set faculty_id='"+id+"', Name ='"+fname+"', qualification='"+qualification+"', designation='"+designation+"', responsibility='"+responsibility+"' where faculty_id='"+id+"';";
    Class.forName("java.sql.Driver");
   conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query1);
    int i = pstmt.executeUpdate();
    if(i>0){
      JOptionPane.showMessageDialog(rootPane, " data is saved");
        idtf.setText(null);
        nametf.setText(null);
        qualitf.setText(null);
        desigtf.setText(null);
        resptf.setText(null);
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " data is not saved");
   }
   }
     catch(Exception e) {
         JOptionPane.showMessageDialog(this,e.getMessage());
     }
}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        panel2.setBackground(paneClick);
        panel3.setBackground(panedefault); 
        panel1.setBackground(panedefault);   

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
  String id = idtf.getText();
  String name = nametf.getText();
   String qualification = qualitf.getText();
        String designation = desigtf.getText();
           String responsibility  = resptf.getText();
           String type =(String) cb1.getSelectedItem().toString();

          if(id.equals("")) {
       JOptionPane.showMessageDialog(rootPane, " Faculty id field is mandatory");
   } 
         else if(name.equals("")) {
       JOptionPane.showMessageDialog(rootPane, " Faculty Name is mandatory");
   }
        else  if(qualification.equals("")) {
       JOptionPane.showMessageDialog(rootPane, "qualification field is mandatory");
   }
        
             
              
          
           
           
          Connection conn=null;
   Statement s1;
   PreparedStatement pstmt=null;
   
   String password = JOptionPane.showInputDialog("Enter the Password: ");
   if(password.equals("admin")){

   try {
       String query= " insert into " + type + " values(?,?,?,?,?);";
    Class.forName("java.sql.Driver");
     conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query);
   pstmt.setString(1, id);
   pstmt.setString(2, name);
   pstmt.setString(3, qualification);
   pstmt.setString(4, designation);
    pstmt.setString(5, responsibility);
    
    int i = pstmt.executeUpdate();
   if(i>0){
      JOptionPane.showMessageDialog(rootPane, " data is saved");
        idtf.setText(null);
        nametf.setText(null);
        qualitf.setText(null);
        desigtf.setText(null);
        resptf.setText(null);
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " data is not saved");
   }
    
          
   }
   
    catch(Exception e) {
        JOptionPane.showMessageDialog(null, e);
     }
   }
          
    else{
    JOptionPane.showMessageDialog(rootPane, " Error, Please try again.");
   }
   
// TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
       panel1.setBackground(paneClick);
        panel3.setBackground(panedefault); 
        panel2.setBackground(panedefault);  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked

        
        Connection conn= null;
   PreparedStatement pstmt=null;
        String id = idtf.getText();
        
String type =(String) cb1.getSelectedItem().toString();
  if(id.isEmpty()){
      JOptionPane.showMessageDialog(rootPane, "Please Enter Faculty ID.");
  }
  else
  {
   

   int x= JOptionPane.showConfirmDialog(null," Do you want to delete the record");
if(x==JOptionPane.YES_OPTION ){
   try {
       String query2= "delete from " +type+ " where faculty_id='"+id+"'";
    Class.forName("java.sql.Driver");
   conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query2);
    int i = pstmt.executeUpdate();
    if(i>0){
      JOptionPane.showMessageDialog(rootPane, " Data is deleted.");
        idtf.setText(null);
        nametf.setText(null);
        qualitf.setText(null);
        desigtf.setText(null);
        resptf.setText(null);
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " Data is not deleted");
   }
   }
     catch(Exception e) {
         JOptionPane.showMessageDialog(this,e.getMessage());
     }
   
}
  }
        // TODO add your handling code here2
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        panel3.setBackground(paneClick);
        panel1.setBackground(panedefault); 
        panel2.setBackground(panedefault); // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        idtf.setText(null);
        nametf.setText(null);
        qualitf.setText(null);
        desigtf.setText(null);
        resptf.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String id= idtf.getText();

String type =(String) cb1.getSelectedItem().toString();
        if(id.isEmpty())
            JOptionPane.showMessageDialog(this, " user id not entered");
        else
        {
            try {

                 Class.forName("java.sql.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
       Statement s1=conn.createStatement();
       String query7="select name,qualification,designation,responsibility from " +type+ " where faculty_id='"+id+"'";
          ResultSet rs=s1.executeQuery(query7);

          int Found=0;
          while(rs.next())
          {
             String name=rs.getString("name");
             String qualification =rs.getString("qualification");
                String designation=rs.getString("designation");
               String responsibility  = rs.getString("responsibility");
               nametf.setText(name);
               qualitf.setText(qualification);
               desigtf.setText(designation);
               resptf.setText(responsibility);
               Found++;
              }
          if(Found==0)
          {
              nametf.setText(null);
        qualitf.setText(null);
        desigtf.setText(null);
        resptf.setText(null);
          
               JOptionPane.showMessageDialog(this, " no such entry found");
          }
         }
       catch(Exception e) {
         JOptionPane.showMessageDialog(this,e.getMessage());
     }

            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseMoved

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
facultyframe ff = new facultyframe();
 this.dispose();
 ff.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
String id = idtf.getText();
  String name = nametf.getText();
   String qualification = qualitf.getText();
        String designation = desigtf.getText();
           String responsibility  = resptf.getText();
           String type =(String) cb1.getSelectedItem().toString();

          if(id.equals("")) {
       JOptionPane.showMessageDialog(rootPane, " Faculty id field is mandatory");
   } 
         else if(name.equals("")) {
       JOptionPane.showMessageDialog(rootPane, " Faculty Name is mandatory");
   }
        else  if(qualification.equals("")) {
       JOptionPane.showMessageDialog(rootPane, "qualification field is mandatory");
   }
        
             
              
          
           
           
          Connection conn=null;
   Statement s1;
   PreparedStatement pstmt=null;
   
   String password = JOptionPane.showInputDialog("Enter the Password: ");
   if(password.equals("admin")){

   try {
       String query= " insert into " + type + " values(?,?,?,?,?);";
    Class.forName("java.sql.Driver");
     conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query);
   pstmt.setString(1, id);
   pstmt.setString(2, name);
   pstmt.setString(3, qualification);
   pstmt.setString(4, designation);
    pstmt.setString(5, responsibility);
    
    int i = pstmt.executeUpdate();
   if(i>0){
      JOptionPane.showMessageDialog(rootPane, " data is saved");
        idtf.setText(null);
        nametf.setText(null);
        qualitf.setText(null);
        desigtf.setText(null);
        resptf.setText(null);
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " data is not saved");
   }
    
          
   }
   
    catch(Exception e) {
        JOptionPane.showMessageDialog(null, e);
     }
   }
          
    else{
    JOptionPane.showMessageDialog(rootPane, " Error, Please try again.");
   }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
   panel1.setBackground(paneClick);
        panel3.setBackground(panedefault); 
        panel2.setBackground(panedefault);  // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
      String id = idtf.getText();
  String fname = nametf.getText();
   String qualification = qualitf.getText();
        String designation = desigtf.getText();
           String responsibility  = resptf.getText();
           String type =(String) cb1.getSelectedItem().toString();
        
        int x= JOptionPane.showConfirmDialog(null," Do you want to update the record");
if(x==JOptionPane.YES_OPTION ){
   try {
       String query1= "UPDATE " + type + " set faculty_id='"+id+"', Name ='"+fname+"', qualification='"+qualification+"', designation='"+designation+"', responsibility='"+responsibility+"' where faculty_id='"+id+"';";
    Class.forName("java.sql.Driver");
   conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query1);
    int i = pstmt.executeUpdate();
    if(i>0){
      JOptionPane.showMessageDialog(rootPane, " data is saved");
        idtf.setText(null);
        nametf.setText(null);
        qualitf.setText(null);
        desigtf.setText(null);
        resptf.setText(null);
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " data is not saved");
   }
   }
     catch(Exception e) {
         JOptionPane.showMessageDialog(this,e.getMessage());
     }
}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
 panel2.setBackground(paneClick);
        panel3.setBackground(panedefault); 
        panel1.setBackground(panedefault);   
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       Connection conn= null;
   PreparedStatement pstmt=null;
        String id = idtf.getText();
        
String type =(String) cb1.getSelectedItem().toString();
  if(id.isEmpty()){
      JOptionPane.showMessageDialog(rootPane, "Please Enter Faculty ID.");
  }
  else
  {
   

   int x= JOptionPane.showConfirmDialog(null," Do you want to delete the record");
if(x==JOptionPane.YES_OPTION ){
   try {
       String query2= "delete from " +type+ " where faculty_id='"+id+"'";
    Class.forName("java.sql.Driver");
   conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query2);
    int i = pstmt.executeUpdate();
    if(i>0){
      JOptionPane.showMessageDialog(rootPane, " Data is deleted.");
        idtf.setText(null);
        nametf.setText(null);
        qualitf.setText(null);
        desigtf.setText(null);
        resptf.setText(null);
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " Data is not deleted");
   }
   }
     catch(Exception e) {
         JOptionPane.showMessageDialog(this,e.getMessage());
     }
   
}
  }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
  panel3.setBackground(paneClick);
        panel1.setBackground(panedefault); 
        panel2.setBackground(panedefault); // TODO add your handling code here:
           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MousePressed

    
       
        
        
       
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addfaculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JTextField desigtf;
    private javax.swing.JTextField idtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nametf;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JTextField qualitf;
    private javax.swing.JTextField resptf;
    // End of variables declaration//GEN-END:variables
}
