
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muzer
 */
public class addstudent extends javax.swing.JFrame {
Color panedefault;
    Color paneClick;
    /**
     * Creates new form addstudent
     */
    public addstudent() {
        initComponents();
        
        panedefault = new Color(51, 0, 102);
        paneClick = new Color(255, 255, 255);
        panel1.setBackground(panedefault);
        panel2.setBackground(panedefault);
         panel2.setBackground(panedefault);
         panel3.setBackground(panedefault);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idtf = new javax.swing.JTextField();
        nametf = new javax.swing.JTextField();
        emailtf = new javax.swing.JTextField();
        cb1 = new javax.swing.JComboBox<>();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        dob1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(51, 0, 102));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel6MouseMoved(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Add Record");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel6.add(jLabel10);
        jLabel10.setBounds(40, 10, 160, 50);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel6.add(panel1);
        panel1.setBounds(0, 0, 30, 70);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(20, 280, 280, 70);

        jPanel7.setBackground(new java.awt.Color(51, 0, 102));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel7MouseMoved(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Back");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(60, 10, 70, 40);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(20, 580, 280, 70);

        jPanel8.setBackground(new java.awt.Color(51, 0, 102));
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel8MouseMoved(evt);
            }
        });
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });
        jPanel8.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Update Record");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        jPanel8.add(jLabel12);
        jLabel12.setBounds(40, 10, 180, 40);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel8.add(panel2);
        panel2.setBounds(0, 0, 30, 70);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(20, 380, 280, 70);

        jPanel9.setBackground(new java.awt.Color(51, 0, 102));
        jPanel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel9MouseMoved(evt);
            }
        });
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });
        jPanel9.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Delete Record");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jPanel9.add(jLabel13);
        jLabel13.setBounds(40, 10, 180, 40);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel9.add(panel3);
        panel3.setBounds(0, 0, 30, 70);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(20, 480, 280, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scsit logo1.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 210, 200);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 820);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("  Student Management");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(120, 50, 700, 100);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(300, 0, 1020, 210);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Select Course");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(50, 30, 190, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Name");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 200, 190, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Email ID");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(50, 290, 190, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Gender");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 460, 190, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Date of Birth");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(50, 380, 190, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Student ID");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(50, 120, 190, 50);

        idtf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(idtf);
        idtf.setBounds(300, 130, 290, 50);

        nametf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(nametf);
        nametf.setBounds(300, 210, 290, 50);

        emailtf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(emailtf);
        emailtf.setBounds(300, 300, 290, 50);

        cb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MCA", "M_TECH", "MBA" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jPanel3.add(cb1);
        cb1.setBounds(300, 40, 290, 50);

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rb1.setText("Male");
        rb1.setOpaque(false);
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        jPanel3.add(rb1);
        rb1.setBounds(310, 470, 150, 40);

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rb2.setText("Female");
        rb2.setOpaque(false);
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        jPanel3.add(rb2);
        rb2.setBounds(500, 470, 170, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("LOAD DATA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(650, 120, 190, 70);

        reset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel3.add(reset);
        reset.setBounds(670, 240, 170, 70);

        dob1.setDateFormatString("yyyy-MM-d");
        dob1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(dob1);
        dob1.setBounds(300, 380, 290, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(300, 210, 1010, 600);

        setSize(new java.awt.Dimension(1355, 856));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseMoved

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked

//    ADD RECORD---------------------------------------------------------------------------------------------------------------------

        String id = idtf.getText();
        String name = nametf.getText();
        String email = emailtf.getText();
        String type =(String) cb1.getSelectedItem().toString();
       String date = ((JTextField)dob1.getDateEditor().getUiComponent()).getText();
        

        if(id.equals("")) {
            JOptionPane.showMessageDialog(rootPane, " Student id field is mandatory");
        }
        if(name.equals("")) {
            JOptionPane.showMessageDialog(rootPane, " Student Name is mandatory");
        }
        if(email.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "email  field is mandatory");
        }
        if(date.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Date of Birth  field is mandatory");
        }
        if(gender.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Gender  field is mandatory");
        }
    //   else
     //   {
     //       JOptionPane.showMessageDialog(rootPane, " Your Details are submitted successfully ");

    //    }

        Connection conn=null;
   Statement s1;
   PreparedStatement pstmt=null;
   
   String password = JOptionPane.showInputDialog("Enter the Password: ");
   if(password.equals("admin")){
        try {
            
            
            String query= " insert into " + type + " values(?,?,?,?,?);";
    Class.forName("java.sql.Driver");
     conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query);
   pstmt.setString(1, id);
   pstmt.setString(2, name);
   pstmt.setString(3, email);
   pstmt.setString(4, date);
    pstmt.setString(5, gender);

    int i = pstmt.executeUpdate();
   if(i>0){
      JOptionPane.showMessageDialog(rootPane, " data is saved");
      idtf.setText(" ");
       nametf.setText(" ");
       emailtf.setText(" ");
         ((JTextField)dob1.getDateEditor().getUiComponent()).setText(" ");
         buttonGroup1.clearSelection();
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " data is not saved");
   }
    
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
   }
   else{
       JOptionPane.showMessageDialog(rootPane, " Error, please try again.");
   }
       idtf.setText(" ");
       nametf.setText(" ");
       emailtf.setText(" ");
         ((JTextField)dob1.getDateEditor().getUiComponent()).setText(" ");
buttonGroup1.clearSelection();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
panel1.setBackground(paneClick);
        panel2.setBackground(panedefault);
         panel3.setBackground(panedefault);
         
        

// panel1.setBackground(paneClick);
      //  panel3.setBackground(panedefault);
      //  panel2.setBackground(panedefault);  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
  gender = "Male";        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
gender = "Female";        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
String type =(String) cb1.getSelectedItem().toString();
if(type.equals("MCA"))
{
    idtf.setText("IC");
}
 
if(type.equals("M_TECH"))
{
    idtf.setText("IT");
}
if(type.equals("MBA"))
{
    idtf.setText("IM");
}
 
 
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void jPanel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseMoved

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked

  studentszone sz = new studentszone();
  this .dispose();
  sz.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MousePressed

    private void jPanel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseMoved

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
 Connection conn=null;
   Statement s1;
   PreparedStatement pstmt=null;
        
        String id = idtf.getText();
        String name = nametf.getText();
        String email = emailtf.getText();
         String type =(String) cb1.getSelectedItem().toString();
       String date = ((JTextField)dob1.getDateEditor().getUiComponent()).getText();
     
      if(rb1.isSelected()==true)
      {
          gender="Male";
         
      }       
      else{
          gender = "Female";
      }
       
  
           
       
       int x= JOptionPane.showConfirmDialog(null," Do you want to update the record");
if(x==JOptionPane.YES_OPTION ) {
    String password = JOptionPane.showInputDialog("Enter the Password: ");
   if(password.equals("admin")){
    try{
        
    
     //  String query1= "UPDATE " + type + " Name ='"+name+"', email_id='"+email+"', dob='"+date+"',gender='"+gender+"' where student_id='"+id+"';";
        
      String query1 = "update " +type+ " set name =?,email_id=? ,dob=? ,gender =? where student_id='"+id+"';";
        
        Class.forName("java.sql.Driver");
   conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query1);
    
  pstmt.setString(1,name);
    pstmt.setString(2,email);
    pstmt.setString(3,date);
    
    pstmt.setString(4,gender);
      
    
    int i = pstmt.executeUpdate();
    if(i>0){
      JOptionPane.showMessageDialog(rootPane, " data is saved");
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " data is not saved");
   }
        
        
    }
    
    
    catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
        
       }
}
    else{
       JOptionPane.showMessageDialog(rootPane, " Error, please try again.");
   }
}

// TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
    panel2.setBackground(paneClick);
        panel1.setBackground(panedefault);
         panel3.setBackground(panedefault);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MousePressed

    private void jPanel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseMoved

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked


String id = idtf.getText();
String type =(String) cb1.getSelectedItem().toString();

Connection conn= null;
   PreparedStatement pstmt=null;

   int x= JOptionPane.showConfirmDialog(null," Do you want to delete the record");
if(x==JOptionPane.YES_OPTION ){
     String password = JOptionPane.showInputDialog("Enter the Password: ");
   if(password.equals("admin")){
    
   try {
       String query2= "delete from " +type+ " where student_id='"+id+"'";
    Class.forName("java.sql.Driver");
   conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query2);
    int i = pstmt.executeUpdate();
    if(i>0){
      JOptionPane.showMessageDialog(rootPane, " Data is deleted.");
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " data is not deleted");
   }
   }
     catch(Exception e) {
         JOptionPane.showMessageDialog(this,e.getMessage());
     }
   }
    else{
    JOptionPane.showMessageDialog(rootPane, " Error, Please try again.");
   }
   
}


        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
    panel3.setBackground(paneClick);
        panel2.setBackground(panedefault);
         panel1.setBackground(panedefault);
                  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id= idtf.getText();

        String type =(String) cb1.getSelectedItem().toString();
        if(id.isEmpty())
        JOptionPane.showMessageDialog(this, " Student id not entered");
        else
        {
            try {

                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
                Statement s1 = conn.createStatement();
                String query7="select name,email_id,dob,gender from " +type+ " where student_id='"+id+"'";
                ResultSet rs=s1.executeQuery(query7);

                int Found=0;
                while(rs.next())
                {
                    String name=rs.getString("name");
                    String email =rs.getString("email_id");
                    String dob=rs.getString("dob");
                    String gender  = rs.getString("gender");
                    nametf.setText(name);
                    emailtf.setText(email);
                    ((JTextField)dob1.getDateEditor().getUiComponent()).setText(dob);
                    if(("Male".equals(rs.getString("gender")))) {
                        
                        rb1.setSelected(true);
                    }
                    else
                        if(("Female".equals(rs.getString("gender")))) {
                        
                        rb2.setSelected(true);
                    }
                                           
                    //desigtf.setText(dob);
                   // resptf.setText(responsibility);
                    Found++;
                }
                 if(Found==0)
                {
                    nametf.setText(null);
                    emailtf.setText(null);
                    ((JTextField)dob1.getDateEditor().getUiComponent()).setText(" ");
                       rb1.setSelected(false); 
                        rb2.setSelected(false);
                               
                    JOptionPane.showMessageDialog(this, " no such entry found");
                     
                }
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
  //idtf.setText(null);
    nametf.setText(null);
  emailtf.setText(null);
   ((JTextField)dob1.getDateEditor().getUiComponent()).setText(" ");
    buttonGroup1.clearSelection();
    cb1.setSelectedIndex(0);
idtf.setText(null);
// TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
Connection conn=null;
   Statement s1;
   PreparedStatement pstmt=null;
        
        String id = idtf.getText();
        String name = nametf.getText();
        String email = emailtf.getText();
         String type =(String) cb1.getSelectedItem().toString();
       String date = ((JTextField)dob1.getDateEditor().getUiComponent()).getText();
     
       
           
       
       int x= JOptionPane.showConfirmDialog(null," Do you want to update the record");
if(x==JOptionPane.YES_OPTION ) {
    String password = JOptionPane.showInputDialog("Enter the Password: ");
   if(password.equals("admin")){
    try{
       // String query1= "UPDATE " + type + " set student_id='"+id+"', Name ='"+name+"', email_id='"+email+"', dob='"+date+"',gender='"+gender+"' where student_id='"+id+"';";
        
        String query1 = "update " +type+ " set name =?,email_id=? ,dob=? ,gender =? where student_id='"+id+"';";
        
        Class.forName("java.sql.Driver");
   conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query1);
    
    pstmt.setString(1,name);
    pstmt.setString(2,email);
    pstmt.setString(3,date);
    if(gender.equals("Male"))
    {
        rb1.setSelected(true);
    }
    
    else
    {
        rb2.setSelected(true);
    }
    pstmt.setString(4,gender);
      
    
    int i = pstmt.executeUpdate();
    if(i>0){
      JOptionPane.showMessageDialog(rootPane, " data is saved");
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " data is not saved");
   }
        
        
    }
    
    
    
    catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
        
       }
}
    else{
       JOptionPane.showMessageDialog(rootPane, " Error, please try again.");
   }
}        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
     String id = idtf.getText();
        String name = nametf.getText();
        String email = emailtf.getText();
        String type =(String) cb1.getSelectedItem().toString();
       String date = ((JTextField)dob1.getDateEditor().getUiComponent()).getText();
        

        if(id.equals("")) {
            JOptionPane.showMessageDialog(rootPane, " Student id field is mandatory");
        }
        if(name.equals("")) {
            JOptionPane.showMessageDialog(rootPane, " Student Name is mandatory");
        }
        if(email.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "email  field is mandatory");
        }
        if(date.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Date of Birth  field is mandatory");
        }
        if(gender.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Gender  field is mandatory");
        }
    //   else
     //   {
     //       JOptionPane.showMessageDialog(rootPane, " Your Details are submitted successfully ");

    //    }

        Connection conn=null;
   Statement s1;
   PreparedStatement pstmt=null;
   
   String password = JOptionPane.showInputDialog("Enter the Password: ");
   if(password.equals("admin")){
        try {
            
            
            String query= " insert into " + type + " values(?,?,?,?,?);";
    Class.forName("java.sql.Driver");
     conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query);
   pstmt.setString(1, id);
   pstmt.setString(2, name);
   pstmt.setString(3, email);
   pstmt.setString(4, date);
    pstmt.setString(5, gender);

    int i = pstmt.executeUpdate();
   if(i>0){
      JOptionPane.showMessageDialog(rootPane, " data is saved");
      idtf.setText(" ");
       nametf.setText(" ");
       emailtf.setText(" ");
         ((JTextField)dob1.getDateEditor().getUiComponent()).setText(" ");
         buttonGroup1.clearSelection();
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " data is not saved");
   }
    
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
   }
   else{
       JOptionPane.showMessageDialog(rootPane, " Error, please try again.");
   }
       idtf.setText(" ");
       nametf.setText(" ");
       emailtf.setText(" ");
         ((JTextField)dob1.getDateEditor().getUiComponent()).setText(" ");
buttonGroup1.clearSelection();
          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
panel1.setBackground(paneClick);
        panel2.setBackground(panedefault);
         panel3.setBackground(panedefault);
          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
  panel2.setBackground(paneClick);
        panel1.setBackground(panedefault);
         panel3.setBackground(panedefault);        // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked


String id = idtf.getText();
String type =(String) cb1.getSelectedItem().toString();

Connection conn= null;
   PreparedStatement pstmt=null;

   int x= JOptionPane.showConfirmDialog(null," Do you want to delete the record");
if(x==JOptionPane.YES_OPTION ){
     String password = JOptionPane.showInputDialog("Enter the Password: ");
   if(password.equals("admin")){
    
   try {
       String query2= "delete from " +type+ " where student_id='"+id+"'";
    Class.forName("java.sql.Driver");
   conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query2);
    int i = pstmt.executeUpdate();
    if(i>0){
      JOptionPane.showMessageDialog(rootPane, " Data is deleted.");
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " data is not deleted");
   }
   }
     catch(Exception e) {
         JOptionPane.showMessageDialog(this,e.getMessage());
     }
   }
    else{
    JOptionPane.showMessageDialog(rootPane, " Error, Please try again.");
   }
   
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
  panel3.setBackground(paneClick);
        panel2.setBackground(panedefault);
         panel1.setBackground(panedefault);
             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb1;
    private com.toedter.calendar.JDateChooser dob1;
    private javax.swing.JTextField emailtf;
    private javax.swing.JTextField idtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField nametf;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables

  private String gender;
}
