
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class forgotpassword extends javax.swing.JFrame {

    String userid;
    
    public forgotpassword() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        secretemail = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        answertf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mobiletf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        questiontf = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        verify = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 0, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Verify Your Account");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(250, 20, 500, 60);

        secretemail.setBackground(new java.awt.Color(51, 0, 255));
        secretemail.setForeground(new java.awt.Color(51, 0, 255));
        jPanel2.add(secretemail);
        secretemail.setBounds(940, 80, 120, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1080, 110);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        answertf.setEditable(false);
        answertf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(answertf);
        answertf.setBounds(470, 490, 450, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Answer");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 490, 170, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Enter Mobile No.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 150, 220, 50);

        mobiletf.setEditable(false);
        mobiletf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(mobiletf);
        mobiletf.setBounds(470, 150, 500, 60);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Security Question");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(150, 420, 220, 50);

        questiontf.setEditable(false);
        questiontf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(questiontf);
        questiontf.setBounds(470, 400, 500, 60);

        submit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(540, 320, 170, 60);

        verify.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        verify.setText("Verify");
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });
        jPanel1.add(verify);
        verify.setBounds(500, 580, 190, 60);

        jRadioButton1.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton1.setText("Via Email");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(620, 70, 190, 40);

        jRadioButton2.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton2.setText("Via Mobile");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(260, 70, 170, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Choose how would you like to verfy your account");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 10, 600, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Enter Email-ID");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(160, 250, 220, 50);

        emailtf.setEditable(false);
        emailtf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(emailtf);
        emailtf.setBounds(470, 240, 500, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 110, 1070, 680);

        setSize(new java.awt.Dimension(1093, 841));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
//  answertf.setEditable(true);
       
String email = emailtf.getText();
String mobile = mobiletf.getText();
// String userid;
String question;
Connection conn= null;
ResultSet rs= null;
PreparedStatement pst =null;
         try {
          Class.forName("com.mysql.jdbc.Driver");
          
          }
         catch(ClassNotFoundException e) {
         System.out.println("Class not found "+ e);
      }
         
         try{
       
           
            conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");

        String query = " select security_question,userid from login where userid = ? or mobile_no =? ;";
        pst=conn.prepareStatement(query);
        pst.setString(1, email);
         pst.setString(2, mobile);   
           rs=pst.executeQuery();
           if(rs.next()==true)
        {
              question = rs.getString("security_question");
              userid =  rs.getString("userid");
           //   secretemail.setText(userid);
              questiontf.setText(question);
           
        }
         }
         
         catch(Exception ex) {
           JOptionPane.showMessageDialog(rootPane, ex);
       }
        
         if((questiontf.getText()).isEmpty()==false){
             answertf.setEditable(true);
         }
         else{
              answertf.setEditable(false);
         }
         
    }//GEN-LAST:event_submitActionPerformed

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
     
        
        Connection conn= null;
ResultSet rs= null;
PreparedStatement pst =null;



    try {
       
               conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");

        String query = " select * from login where security_question = ? and security_answer = ?;";
        pst=conn.prepareStatement(query);
        pst.setString(1, questiontf.getText());
        pst.setString(2,  answertf.getText());
        
        rs=pst.executeQuery();
        if(rs.next())
        {
             JOptionPane.showMessageDialog(null, "Account Verified Successfully");
             resetframe rf = new resetframe(userid);
             
            this.dispose();
            rf.setVisible(true);
             }
        else
        {
             JOptionPane.showMessageDialog(null, "Verification Failed. please try again.");
        }
        conn.close();
    } 
    
    
    
    catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    
        

// TODO add your handling code here:
    }//GEN-LAST:event_verifyActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       mobiletf.setEditable(true);
       emailtf.setText("");
       emailtf.setEditable(false);
       questiontf.setText("");
       secretemail.setText("");
        answertf.setEditable(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
     emailtf.setEditable(true);
     mobiletf.setText("");
       mobiletf.setEditable(false);
       questiontf.setText("");
        answertf.setEditable(false);
        secretemail.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpassword().setVisible(true);
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answertf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField emailtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField mobiletf;
    private javax.swing.JTextField questiontf;
    private javax.swing.JLabel secretemail;
    private javax.swing.JButton submit;
    private javax.swing.JButton verify;
    // End of variables declaration//GEN-END:variables
}
