
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muzer
 */
public class programmesframe extends javax.swing.JFrame {
Color panedefault;
    Color paneClick;
    /**
     * Creates new form programmesframe
     */
    public programmesframe() {
        initComponents();
        panedefault = new Color(85, 65, 118);
        paneClick = new Color(255, 255, 255);
        panel1.setBackground(panedefault);
        
         panel2.setBackground(panedefault);
         panel3.setBackground(panedefault);
        // panel4.setBackground(panedefault);
        
          ImageIcon icon = new ImageIcon("C:/Users/HP/Downloads/scsit logo.jpeg");
    Image image = icon.getImage().getScaledInstance(imglbl.getWidth(),imglbl.getHeight(),Image.SCALE_SMOOTH);
    imglbl.setIcon(icon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        blabel = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        label1 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        panel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imglbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 33, 69));
        jPanel1.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(85, 65, 118));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(null);

        blabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blabel.setForeground(new java.awt.Color(255, 255, 255));
        blabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        blabel.setText("BACK");
        blabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                blabelMouseMoved(evt);
            }
        });
        blabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blabelMouseClicked(evt);
            }
        });
        jPanel8.add(blabel);
        blabel.setBounds(40, 10, 90, 40);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(40, 390, 280, 60);

        jPanel38.setBackground(new java.awt.Color(85, 65, 118));
        jPanel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel38MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel38MousePressed(evt);
            }
        });
        jPanel38.setLayout(null);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel38.add(panel1);
        panel1.setBounds(0, 0, 30, 70);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("UG COURSE");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel38.add(jLabel6);
        jLabel6.setBounds(40, 10, 220, 40);

        jPanel1.add(jPanel38);
        jPanel38.setBounds(40, 60, 280, 60);

        jPanel39.setBackground(new java.awt.Color(85, 65, 118));
        jPanel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel39MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel39MousePressed(evt);
            }
        });
        jPanel39.setLayout(null);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel39.add(panel2);
        panel2.setBounds(0, 0, 30, 70);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PG Course");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel39.add(jLabel7);
        jLabel7.setBounds(40, 10, 130, 40);

        jPanel1.add(jPanel39);
        jPanel39.setBounds(40, 240, 280, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 140, 320, 560);

        jDesktopPane1.setBackground(new java.awt.Color(204, 255, 255));

        table1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Course duration", "Program Incharge"
            }
        ));
        table1.setGridColor(new java.awt.Color(255, 102, 102));
        table1.setRowHeight(35);
        table1.setRowMargin(2);
        table1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(table1);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 990, 340);

        label1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jDesktopPane1.add(label1);
        label1.setBounds(70, 10, 710, 100);

        jPanel40.setBackground(new java.awt.Color(85, 65, 118));
        jPanel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel40MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel40MousePressed(evt);
            }
        });
        jPanel40.setLayout(null);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel40.add(panel3);
        panel3.setBounds(0, 0, 30, 70);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("UG Course");
        jPanel40.add(jLabel8);
        jLabel8.setBounds(40, 10, 130, 40);

        jDesktopPane1.add(jPanel40);
        jPanel40.setBounds(170, 190, 270, 60);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(310, 140, 1010, 560);

        jPanel2.setBackground(new java.awt.Color(51, 33, 69));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    COURSES");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(600, 30, 450, 80);

        imglbl.setText("jLabel2");
        jPanel2.add(imglbl);
        imglbl.setBounds(0, 0, 320, 180);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 140);

        setSize(new java.awt.Dimension(1322, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void blabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blabelMouseMoved
             blabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        // TODO add your handling code here:
    }//GEN-LAST:event_blabelMouseMoved

    private void blabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blabelMouseClicked
        scsithomeframe ip = new scsithomeframe();
        this.dispose();
        ip.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_blabelMouseClicked

    private void jPanel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel38MouseClicked

label1.setText(" UG  Courses  at  SCSIT");
table1.setModel(new DefaultTableModel (null, new String[] {"course_id","course_name","course_duration","program_incharge"}));
DefaultTableModel m1=(DefaultTableModel)table1.getModel();
try{
       Class.forName("java.sql.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
       Statement s1=conn.createStatement();

       String q1="select*from ugcourse;";
       ResultSet rs=s1.executeQuery(q1);
       while(rs.next()){
       String course_id= rs.getString("course_id");
       String course_name= rs.getString("Name");
       String course_duration= rs.getString("duration");
       String program_incharge= rs.getString("program_incharge");
       m1.addRow(new Object[]{course_id,course_name,course_duration,program_incharge});

       }
       rs.close();
       s1.close();
       conn.close();
       
       
       
}

catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }


        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel38MouseClicked

    private void jPanel38MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel38MousePressed



panel1.setBackground(paneClick);
       
        panel2.setBackground(panedefault);
        panel3.setBackground(panedefault); 
// TODO add your handling code here:
    }//GEN-LAST:event_jPanel38MousePressed

    private void jPanel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel39MouseClicked
label1.setText(" PG  Courses  at  SCSIT");
table1.setModel(new DefaultTableModel (null, new String[] {"course_id","course_name","course_duration","program_incharge"}));
DefaultTableModel m1=(DefaultTableModel)table1.getModel();
try{
       Class.forName("java.sql.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
       Statement s1=conn.createStatement();

       String q1="select * from pgcourse;";
       ResultSet rs=s1.executeQuery(q1);
       while(rs.next()){
       String course_id= rs.getString("course_id");
       String course_name= rs.getString("Name");
       String course_duration= rs.getString("duration");
       String program_incharge= rs.getString("program_incharge");
       //String responsibility=rs.getString("Responsibility");
       m1.addRow(new Object[]{course_id,course_name,course_duration,program_incharge});

       }
       rs.close();
       s1.close();
       conn.close();
       
       
       
}

catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel39MouseClicked

    private void jPanel39MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel39MousePressed
panel2.setBackground(paneClick);
        panel1.setBackground(panedefault);
        panel3.setBackground(panedefault); 
       
// TODO add your handling code here:
    }//GEN-LAST:event_jPanel39MousePressed

    private void jPanel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel40MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel40MouseClicked

    private void jPanel40MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel40MousePressed
     panel3.setBackground(paneClick);
        panel1.setBackground(panedefault);
        panel2.setBackground(panedefault); 
   // TODO add your handling code here:
    }//GEN-LAST:event_jPanel40MousePressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

label1.setText(" UG  Courses  at  SCSIT");
table1.setModel(new DefaultTableModel (null, new String[] {"course_id","course_name","course_duration","program_incharge"}));
DefaultTableModel m1=(DefaultTableModel)table1.getModel();
try{
       Class.forName("java.sql.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
       Statement s1=conn.createStatement();

       String q1="select*from ugcourse;";
       ResultSet rs=s1.executeQuery(q1);
       while(rs.next()){
       String course_id= rs.getString("course_id");
       String course_name= rs.getString("Name");
       String course_duration= rs.getString("duration");
       String program_incharge= rs.getString("program_incharge");
       //String responsibility=rs.getString("Responsibility");
       m1.addRow(new Object[]{course_id,course_name,course_duration,program_incharge});

       }
       rs.close();
       s1.close();
       conn.close();
       
       
       
}

catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
label1.setText(" PG  Courses  at  SCSIT");
table1.setModel(new DefaultTableModel (null, new String[] {"course_id","course_name","course_duration","program_incharge"}));
DefaultTableModel m1=(DefaultTableModel)table1.getModel();
try{
       Class.forName("java.sql.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
       Statement s1=conn.createStatement();

       String q1="select*from pgcourse;";
       ResultSet rs=s1.executeQuery(q1);
       while(rs.next()){
       String course_id= rs.getString("course_id");
       String course_name= rs.getString("Name");
       String course_duration= rs.getString("duration");
       String program_incharge= rs.getString("program_incharge");
       
       m1.addRow(new Object[]{course_id,course_name,course_duration,program_incharge});

       }
       rs.close();
       s1.close();
       conn.close();
       
       
       
}

catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
scsithomeframe ip = new scsithomeframe();
        this.dispose();
        ip.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed

panel1.setBackground(paneClick);
       
        panel2.setBackground(panedefault);
        panel3.setBackground(panedefault);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
panel2.setBackground(paneClick);
        panel1.setBackground(panedefault);
        panel3.setBackground(panedefault); 
         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programmesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programmesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programmesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programmesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programmesframe().setVisible(true);
            }
        });
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blabel;
    private javax.swing.JLabel imglbl;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
