
import java.awt.Color;
import java.awt.Cursor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muzer
 */
public class scsithomeframe extends javax.swing.JFrame {
Color panedefault;
    Color paneClick;
    
    /**
     * Creates new form iipsframe
     */
    public scsithomeframe() {
        initComponents();
        
          panedefault = new Color(85,65,118);
        paneClick = new Color(255, 255, 255);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        aboutlabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        plabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        alabel = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        logoutlabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 33, 69));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(85, 65, 118));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(null);

        aboutlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        aboutlabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutlabel.setText("ABOUT");
        aboutlabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                aboutlabelMouseMoved(evt);
            }
        });
        aboutlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutlabelMouseEntered(evt);
            }
        });
        jPanel3.add(aboutlabel);
        aboutlabel.setBounds(50, 10, 160, 40);

        jPanel5.setBackground(new java.awt.Color(85, 65, 118));
        jPanel5.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HOME");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(70, 10, 230, 40);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(540, 340, 340, 60);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(40, 40, 250, 60);

        jPanel7.setBackground(new java.awt.Color(85, 65, 118));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(null);

        plabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        plabel.setForeground(new java.awt.Color(255, 255, 255));
        plabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plabel.setText("PROGRAMMES");
        plabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                plabelMouseMoved(evt);
            }
        });
        plabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plabelMouseClicked(evt);
            }
        });
        jPanel7.add(plabel);
        plabel.setBounds(40, 10, 200, 40);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(40, 140, 250, 60);

        jPanel8.setBackground(new java.awt.Color(85, 65, 118));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(null);

        alabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        alabel.setForeground(new java.awt.Color(255, 255, 255));
        alabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alabel.setText("ACADEMICS");
        alabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                alabelMouseMoved(evt);
            }
        });
        alabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alabelMouseClicked(evt);
            }
        });
        jPanel8.add(alabel);
        alabel.setBounds(50, 10, 170, 40);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(40, 250, 250, 60);

        jPanel16.setBackground(new java.awt.Color(85, 65, 118));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
        });
        jPanel16.setLayout(null);

        logoutlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logoutlabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutlabel.setText("LOGOUT");
        logoutlabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logoutlabelMouseMoved(evt);
            }
        });
        logoutlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutlabelMouseClicked(evt);
            }
        });
        jPanel16.add(logoutlabel);
        logoutlabel.setBounds(40, 10, 200, 40);

        jPanel1.add(jPanel16);
        jPanel16.setBounds(40, 360, 250, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 130, 290, 530);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("UGC-SAP Supported ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(570, 80, 520, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("School of Computer Science & Information Technology");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(240, 0, 1070, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("DEVI AHILYA UNIVERSITY INDORE");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(440, 40, 720, 44);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1310, 130);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\scsit director.jpeg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 180, 480, 480);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("Message from Director...");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 130, 450, 44);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jTextArea2.setRows(25);
        jTextArea2.setTabSize(10);
        jTextArea2.setText("The School of Computer Science & \nInformation Technology (SCSIT), \nearlier it was Institute of Computer\n Science and Electronics (ICSE) was\n established in 1986 with funding \nfrom UGC for MCA programme. Later,\n the School started M.Sc.(Computer\n Science) in 1987 with 2 crore \nfunding from DRDO. Also, M.Tech \n(Computer Science) programme was \nstarted in 1992 approved by AICTE.\n M.Tech (Network Management & \nInformation Security) and M.Tech \n(Software Engineering & Information\n Architecture) was started in 2009 approved \nby AICTE. Keeping in view the social\n needs in the area of information technology,\n the department is also running MBA\n (Computer Management), M.Sc.\n (Information Technology) and BCA \nprogramme on self supported basis. \nThe School is running PhD (Computer \nScience) programme in a variety of \ndomains.");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(770, 130, 540, 530);

        setSize(new java.awt.Dimension(1331, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutlabelMouseClicked
this.dispose();
        aboutframe ab= new aboutframe();
       ab.setVisible(true);
       

        // TODO add your handling code here:
    }//GEN-LAST:event_aboutlabelMouseClicked

    private void aboutlabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutlabelMouseMoved
aboutlabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_aboutlabelMouseMoved

    private void plabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plabelMouseMoved
plabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_plabelMouseMoved

    private void alabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alabelMouseMoved
alabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_alabelMouseMoved

    private void logoutlabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutlabelMouseMoved
   logoutlabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));      // TODO add your handling code here:
    }//GEN-LAST:event_logoutlabelMouseMoved

    private void logoutlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutlabelMouseClicked

        loginframe lf = new loginframe();
        this.dispose();
lf.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutlabelMouseClicked

    private void plabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plabelMouseClicked
   programmesframe pf =  new programmesframe();
   this.dispose();
   pf.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_plabelMouseClicked

    private void alabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alabelMouseClicked


    academicsframe af = new academicsframe();
    this.dispose();
    af.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_alabelMouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
academicsframe af = new academicsframe();
 this.dispose();
af.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
    programmesframe pf =  new programmesframe();
   this.dispose();
   pf.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
    this.dispose();
        aboutframe ab= new aboutframe();
       ab.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
   loginframe lf = new loginframe();
        this.dispose();
lf.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16MouseClicked

    private void aboutlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutlabelMouseEntered
  this.dispose();
        aboutframe ab= new aboutframe();
       ab.setVisible(true);        // TODO add your handling code here:
           // TODO add your handling code here:
    }//GEN-LAST:event_aboutlabelMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scsithomeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scsithomeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scsithomeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scsithomeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scsithomeframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutlabel;
    private javax.swing.JLabel alabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel logoutlabel;
    private javax.swing.JLabel plabel;
    // End of variables declaration//GEN-END:variables
}
