
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author salik shafi
 */
public class signupframe extends javax.swing.JFrame {

    /**
     * Creates new form signupframe
     */
    public signupframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fnametf = new javax.swing.JTextField();
        lnametf = new javax.swing.JTextField();
        answertf = new javax.swing.JTextField();
        npass = new javax.swing.JPasswordField();
        SIGNUP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cpass = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        mobiletf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 0, 255));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 10, 150, 800);

        jPanel4.setBackground(new java.awt.Color(51, 0, 255));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTER AS NEW USER");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(260, 20, 590, 60);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 1050, 100);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Choose your security Question");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 550, 380, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Last Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 200, 170, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("First Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 130, 170, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Enter Email-ID");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 260, 190, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Create Password");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 330, 210, 50);

        fnametf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(fnametf);
        fnametf.setBounds(640, 120, 330, 50);

        lnametf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(lnametf);
        lnametf.setBounds(640, 190, 330, 50);

        answertf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(answertf);
        answertf.setBounds(640, 630, 330, 50);

        npass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(npass);
        npass.setBounds(640, 330, 330, 50);

        SIGNUP.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        SIGNUP.setText("SIGNUP");
        SIGNUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGNUPActionPerformed(evt);
            }
        });
        jPanel1.add(SIGNUP);
        SIGNUP.setBounds(590, 710, 190, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Back To Login");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 780, 140, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Answer");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(220, 620, 230, 50);

        cb1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What was your first nick name?", "What was your first mobile no?", "Which was your first car?" }));
        jPanel1.add(cb1);
        cb1.setBounds(640, 550, 330, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Mobile No.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(190, 470, 230, 50);

        cpass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(cpass);
        cpass.setBounds(640, 400, 330, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Confirm Password");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(190, 400, 230, 50);

        emailtf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(emailtf);
        emailtf.setBounds(640, 260, 330, 50);

        mobiletf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(mobiletf);
        mobiletf.setBounds(640, 470, 330, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1050, 810);

        setSize(new java.awt.Dimension(1071, 862));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SIGNUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGNUPActionPerformed
String fname = fnametf.getText();
String lname = lnametf.getText();
String email = emailtf.getText(); 
String newpass = new String( npass.getPassword());
String conpass = new String( cpass.getPassword());
String mobile = mobiletf.getText();
String question =(String) cb1.getSelectedItem().toString();
String answer = answertf.getText();

if((newpass).equals(conpass)){
    
     Connection conn=null;
   Statement s1;
   PreparedStatement pstmt=null;
        try {
            
            
            String query= " insert into login values(?,?,?,?,?,?,?);";
    Class.forName("java.sql.Driver");
     conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
    pstmt=  (PreparedStatement) conn.prepareStatement(query);
   pstmt.setString(1, fname);
   pstmt.setString(2, lname);
   pstmt.setString(3, email);
   pstmt.setString(4, conpass);
   pstmt.setString(5, mobile);
   pstmt.setString(6, question);
   pstmt.setString(7, answer);
   

    int i = pstmt.executeUpdate();
   if(i>0){
      JOptionPane.showMessageDialog(rootPane, " Registered Successfully");
      fnametf.setText(null);
        lnametf.setText(null);
        answertf.setText(null);
        npass.setText(null);
        cpass.setText(null);
        loginframe lf = new loginframe();
        this.dispose();
        lf.setVisible(true);
   }
   else{
    JOptionPane.showMessageDialog(rootPane, " Error, Try Again");
   }
    
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
          
}

   else
{
    JOptionPane.showMessageDialog(rootPane, " password do not match");
}









// TODO add your handling code here:
    }//GEN-LAST:event_SIGNUPActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
   loginframe lf = new loginframe();
   this.dispose();
   lf.setVisible(true);
        


// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SIGNUP;
    private javax.swing.JTextField answertf;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JTextField emailtf;
    private javax.swing.JTextField fnametf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lnametf;
    private javax.swing.JTextField mobiletf;
    private javax.swing.JPasswordField npass;
    // End of variables declaration//GEN-END:variables
}
