import java.awt.Color;
import javax.swing.UIDefaults;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        progress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel1.setText("SCSIT   MANAGEMENT   SYSTEM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 150, 790, 90);

        bar.setBackground(new java.awt.Color(0, 102, 255));
        bar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bar.setForeground(new java.awt.Color(0, 0, 0));
        bar.setFocusable(false);
        jPanel1.add(bar);
        bar.setBounds(60, 410, 960, 60);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel2.setText("Welcome   To... ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 30, 430, 90);

        progress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        progress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progress.setText("0 %");
        jPanel1.add(progress);
        progress.setBounds(500, 420, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1090, 600);

        setSize(new java.awt.Dimension(1089, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         
        Splash sp = new Splash();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sp.setVisible(true);
               
                
                
            }
        });
       sp.bar.setStringPainted(true);

 UIManager.put("sp.bar.background", Color.BLACK);
    UIManager.put("sp.bar.foreground", Color.RED);
  //  UIManager.put("sp.bar.selectionBackground", Color.YELLOW);
   // UIManager.put("sp.bar.selectionForeground", Color.BLUE);
 //   final JProgressBar progressBar = new JProgressBar();
       
        try {
            for(int i =0; i<=100; i++)
            {
                Thread.sleep(40);
                sp.bar.setValue(i);
              //  sp.progress.setText(Integer.toString((i))+"%");
                sp.bar.setValue(i);
                
                 
            }
            
            sp.dispose();
            
        }
        catch (Exception e) 
        {
            
        }
        
         sp.dispose();
        loginframe lf = new loginframe();
        lf.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel progress;
    // End of variables declaration//GEN-END:variables
}
