
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.*;
import javax.swing.table.TableColumnModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muzer
 */
public class studentszone extends javax.swing.JFrame {
Color panedefault;
    Color paneClick;
    /**
     * Creates new form studentszone
     */
   
    
    public studentszone() {
        initComponents();
        
        panedefault = new Color(51, 0, 102);
        paneClick = new Color(255, 255, 255);
        panel1.setBackground(panedefault);
        panel2.setBackground(panedefault);
         panel3.setBackground(panedefault);
         panel4.setBackground(panedefault);
         
         JTableHeader tableHeader = table1.getTableHeader();
        
        Font headerFont = new Font("Verdana", Font.BOLD, 22);
        tableHeader.setFont(headerFont);
        tableHeader.setBackground(Color.black);
        
        TableColumnModel tcm = table1.getColumnModel();
        TableColumn column = null;
        
        for(int i = 0; i < 2; i++)
        {
            
            column = table1.getColumnModel().getColumn(i);
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            column.setCellRenderer(tcr);
                     
            if (i==0) {
                column.setPreferredWidth(50);
            }
            else{
                if(i==1){
                    column.setPreferredWidth(185);
                }
        
            }
        
        }
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        backlabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("STUDENTS ZONE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 30, 490, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(300, 0, 1140, 140);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(51, 0, 102));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("B.COM");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(50, 10, 90, 40);

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel4.add(panel4);
        panel4.setBounds(0, 0, 40, 70);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(30, 410, 270, 70);

        jPanel5.setBackground(new java.awt.Color(51, 0, 102));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MCA");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jPanel5.add(jLabel13);
        jLabel13.setBounds(60, 10, 80, 40);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel5.add(panel1);
        panel1.setBounds(0, 0, 40, 60);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(30, 170, 270, 60);

        jPanel7.setBackground(new java.awt.Color(51, 0, 102));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("M-TECH");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        jPanel7.add(jLabel14);
        jLabel14.setBounds(60, 10, 100, 40);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel7.add(panel2);
        panel2.setBounds(0, 0, 40, 60);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(30, 250, 270, 60);

        jPanel9.setBackground(new java.awt.Color(51, 0, 102));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });
        jPanel9.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("MBA");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel9.add(jLabel15);
        jLabel15.setBounds(60, 10, 60, 40);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel9.add(panel3);
        panel3.setBounds(0, 0, 40, 60);

        jPanel2.add(jPanel9);
        jPanel9.setBounds(30, 330, 270, 60);

        jPanel6.setBackground(new java.awt.Color(51, 0, 102));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Manage Students");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(10, 10, 210, 40);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(30, 500, 270, 60);

        jPanel8.setBackground(new java.awt.Color(51, 0, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(null);

        backlabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backlabel1.setForeground(new java.awt.Color(255, 255, 255));
        backlabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backlabel1.setText("BACK");
        backlabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backlabel1MouseMoved(evt);
            }
        });
        backlabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlabel1MouseClicked(evt);
            }
        });
        jPanel8.add(backlabel1);
        backlabel1.setBounds(50, 10, 100, 40);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(30, 580, 270, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 300, 780);

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setLayout(null);

        table1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Email ID", "DOB", "Gender"
            }
        ));
        table1.setIntercellSpacing(new java.awt.Dimension(2, 2));
        table1.setRowHeight(30);
        table1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(table1);

        jPanel11.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 1060, 490);

        label1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel11.add(label1);
        label1.setBounds(10, 10, 820, 70);

        getContentPane().add(jPanel11);
        jPanel11.setBounds(300, 140, 1130, 640);

        setSize(new java.awt.Dimension(1393, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
               // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked

        
label1.setText(" List of Students in MCA programme");
        //table1.setModel(new DefaultTableModel (null, new String[] {"faculty_id","name","qualification","designation","responsibility"}));
        table1.setModel(new DefaultTableModel (null, new String[] {"Student_Id","Name","Email_Id","Date of Birth","Gender"}));
        DefaultTableModel m1=(DefaultTableModel)table1.getModel();
        
try{
       Class.forName("java.sql.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
       Statement s1=conn.createStatement();

       String q1="select*from mca";
       ResultSet rs=s1.executeQuery(q1);
       while(rs.next()){
       String Student_id= rs.getString("Student_id");
       String name= rs.getString("Name");
       String email_id= rs.getString("email_id");
       String dob = rs.getString("DOB");
       String gender = rs.getString("Gender");
       m1.addRow(new Object[]{Student_id,name,email_id,dob,gender});

       }
       rs.close();
       s1.close();
       conn.close();
}
catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }

     
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
label1.setText(" List of Students in M-TECH programme");
table1.setModel(new DefaultTableModel (null, new String[] {"student_id","name","email_id","dob","gender"}));
        DefaultTableModel m1=(DefaultTableModel)table1.getModel();
        
try{
       Class.forName("java.sql.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
       Statement s1=conn.createStatement();

       String q1="select*from m_tech";
       ResultSet rs=s1.executeQuery(q1);
       while(rs.next()){
       String student_id= rs.getString("student_id");
       String name= rs.getString("Name");
       String email_id= rs.getString("email_id");
       String dob = rs.getString("DOB");
       String gender = rs.getString("Gender");
       m1.addRow(new Object[]{student_id,name,email_id,dob,gender});

       }
       rs.close();
       s1.close();
       conn.close();
}
catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }


        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked

        label1.setText(" List of Students in MBA programme");
        
        table1.setModel(new DefaultTableModel (null, new String[] {"student_id","name","email_id","dob","gender"}));
        DefaultTableModel m1=(DefaultTableModel)table1.getModel();
        
try{
       Class.forName("java.sql.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
       Statement s1=conn.createStatement();

       String q1="select*from mba";
       ResultSet rs=s1.executeQuery(q1);
       while(rs.next()){
       String student_id= rs.getString("student_id");
       String name= rs.getString("Name");
       String email_id= rs.getString("email_id");
       String dob = rs.getString("DOB");
       String gender = rs.getString("Gender");
       m1.addRow(new Object[]{student_id,name,email_id,dob,gender});

       }
       rs.close();
       s1.close();
       conn.close();
}
catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
panel1.setBackground(paneClick);
        panel2.setBackground(panedefault);
         panel3.setBackground(panedefault);
         panel4.setBackground(panedefault);
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
panel2.setBackground(paneClick);
        panel1.setBackground(panedefault);
         panel3.setBackground(panedefault);
         panel4.setBackground(panedefault);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MousePressed

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
panel3.setBackground(paneClick);
        panel2.setBackground(panedefault);
         panel1.setBackground(panedefault);
         panel4.setBackground(panedefault);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MousePressed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
panel4.setBackground(paneClick);
        panel2.setBackground(panedefault);
         panel3.setBackground(panedefault);
         panel1.setBackground(panedefault);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked

addstudent as = new addstudent();
this.dispose();
as.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void backlabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabel1MouseMoved
        //   backlabel1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        // TODO add your handling code here:
    }//GEN-LAST:event_backlabel1MouseMoved

    private void backlabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabel1MouseClicked
        scsithomeframe ip = new scsithomeframe();
        this.dispose();
        ip.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backlabel1MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked

        academicsframe af = new academicsframe();
        this.dispose();
        af.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
label1.setText(" List of Students in MCA programme");
        //table1.setModel(new DefaultTableModel (null, new String[] {"faculty_id","name","qualification","designation","responsibility"}));
        table1.setModel(new DefaultTableModel (null, new String[] {"student_id","name","email_id","dob","gender"}));
        DefaultTableModel m1=(DefaultTableModel)table1.getModel();
        
try{
       Class.forName("java.sql.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
       Statement s1=conn.createStatement();

       String q1="select*from mca";
       ResultSet rs=s1.executeQuery(q1);
       while(rs.next()){
       String student_id= rs.getString("student_id");
       String name= rs.getString("Name");
       String email_id= rs.getString("email_id");
       String dob = rs.getString("DOB");
       String gender = rs.getString("Gender");
       m1.addRow(new Object[]{student_id,name,email_id,dob,gender});

       }
       rs.close();
       s1.close();
       conn.close();
}
catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }

     
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
panel1.setBackground(paneClick);
        panel2.setBackground(panedefault);
         panel3.setBackground(panedefault);
         panel4.setBackground(panedefault);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
label1.setText(" List of Students in M-TECH programme");
table1.setModel(new DefaultTableModel (null, new String[] {"student_id","name","email_id","dob","gender"}));
        DefaultTableModel m1=(DefaultTableModel)table1.getModel();
        
try{
       Class.forName("java.sql.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
       Statement s1=conn.createStatement();

       String q1="select*from m_tech";
       ResultSet rs=s1.executeQuery(q1);
       while(rs.next()){
       String student_id= rs.getString("student_id");
       String name= rs.getString("Name");
       String email_id= rs.getString("email_id");
       String dob = rs.getString("DOB");
       String gender = rs.getString("Gender");
       m1.addRow(new Object[]{student_id,name,email_id,dob,gender});

       }
       rs.close();
       s1.close();
       conn.close();
}
catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
panel2.setBackground(paneClick);
        panel1.setBackground(panedefault);
         panel3.setBackground(panedefault);
         panel4.setBackground(panedefault);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MousePressed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

        label1.setText(" List of Students in MBA programme");
        
        table1.setModel(new DefaultTableModel (null, new String[] {"student_id","name","email_id","dob","gender"}));
        DefaultTableModel m1=(DefaultTableModel)table1.getModel();
        
try{
       Class.forName("java.sql.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/college","root","1234");
       Statement s1=conn.createStatement();

       String q1="select*from mba";
       ResultSet rs=s1.executeQuery(q1);
       while(rs.next()){
       String student_id= rs.getString("student_id");
       String name= rs.getString("Name");
       String email_id= rs.getString("email_id");
       String dob = rs.getString("DOB");
       String gender = rs.getString("Gender");
       m1.addRow(new Object[]{student_id,name,email_id,dob,gender});

       }
       rs.close();
       s1.close();
       conn.close();
}
catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        // TODO add your handling code here:
                                        
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
panel3.setBackground(paneClick);
        panel2.setBackground(panedefault);
         panel1.setBackground(panedefault);
         panel4.setBackground(panedefault);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        int i=0;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentszone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentszone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentszone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentszone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        studentszone sz = new studentszone();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sz.setVisible(true);
            }
        });
  
    /*    
        
        JTableHeader tableHeader = sz.table1.getTableHeader();
        
        Font headerFont = new Font("Verdana", Font.BOLD, 22);
        tableHeader.setFont(headerFont);
        tableHeader.setBackground(Color.black);
        
        TableColumnModel tcm = sz.table1.getColumnModel();
        TableColumn column = null;
        
        for( i = 0; i < 2; i++)
        {
            
            column = sz.table1.getColumnModel().getColumn(i);
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            column.setCellRenderer(tcr);
                     
            if (i==0) {
                column.setPreferredWidth(50);
            }
            else{
                if(i==1){
                    column.setPreferredWidth(185);
                }
        
            }
        
        }
        
        
        
        
        
        
        
        
      //    TableColumnModel tcm = sz.table1.getColumnModel();
      //    TableColumn column = null;
        column = sz.table1.getColumnModel().getColumn(i);
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            column.setCellRenderer(tcr);
            
        
     */   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backlabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
